baseURL = "https://raditian-hugo.radity.com/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


[menu]

  [[menu.header]]
  name = "About the Book"
  URL = "#aboutBook"
  weight = 2

  [[menu.header]]
  name = "About Me"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Start Today"
  URL = "#buyNow"
  weight = 4

  [[menu.header]]
  name = "The first 10 pages"
  URL = "#contact"
  weight = 5

 [[menu.footer]]
  name = "About the Book"
  URL = "#aboutBook"
  weight = 2

  [[menu.footer]]
  name = "About Me"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Start Today"
  URL = "#buyNow"
  weight = 4

  [[menu.footer]]
  name = "The first 10 pages"
  URL = "#contact"
  weight = 5


[params]

  sections = ["showcase", "aboutBook",  "aboutMe", "buyNow", "education", "experience","contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

[params.logo]
    text1 = "Get Into UK law School"
    text2 = ""
    [params.footer]
      copyright = "Â© Aaron Leong. All rights reserved."
